### ISSUE TITLE
Проблема с выпадающим списком.

### ISSUE THREAD

**Issue by EddieBro** [Denis74RUS/autorep#5]
Выпадающий список виден только по когда мы на главной и на /postlist'e 

Т.к. categories только в главной и в /postlit вьюхах, есть ли способ сделать "общую" вьюху, чтобы не дублировать код в для каждой страницы.

**Comment by Denis74RUS** [comment]
Добавил categories в @main.context_processor. Теперь они будут доступны для всех views из main.
