### ISSUE TITLE
youtube плагин для ckeditor'a 

### ISSUE THREAD

**Issue by EddieBro** [Denis74RUS/autorep#6]
http://ckeditor.com/addon/youtube нашел такую штуку, посмотришь как прилепить к нашему ckedtior'у ?
Просто "вкидывание" ссылок не помогает.

**Comment by EddieBro** [comment]
да, еще к ckeditor'у в догонку
Ckeditor (добавить размер шрифта \ семейство шрифта \ цвет текста ).
Сегодня показывал админку и как что делать клиенту, так что может это будет не единичный запрос по ckeditor'у.

**Comment by Denis74RUS** [comment]
Установил локально CKEditor (раньше был CDN) и плагин Youtube. CKEditor определяется по ID="longText", поэтому убрал widget из admin/forms.py, который раньше добавлял класс "ckeditor" для textarea.
